name: PublishVersion
on: [push, pull_request]
jobs:
  # code checkout 
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        #### CHECKOUT MASTER/MAIN BRANCH
        uses: actions/checkout@v2.4.0

  # create and publish release
  release:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - name: release
        uses: CupOfTea696/gh-action-auto-release@v1.0.0
        with:
          title: "Release: $version"
          tag: "v$semver"
          draft: false
          regex: "Release.*"
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}