name: PublishVersion
on: 
  push:
    branches:
    - main

jobs:
  # code checkout 
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        #### CHECKOUT MASTER/MAIN BRANCH
        uses: actions/checkout@v2.4.0

  # create release
  release:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - name: release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          tag: 0.0.1
        #uses: release-drafter/release-drafter@v5