name: PublishVersion
on: 
  push:
    branches:
    - main

jobs:
  # code checkout 
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        #### CHECKOUT MASTER/MAIN BRANCH
        uses: actions/checkout@v2.4.0

  # create release
  release:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - name: release
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}